name: mlstream
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - alabaster=0.7.12=py_0
  - attrs=19.3.0=py_0
  - babel=2.7.0=py_0
  - backcall=0.1.0=py_0
  - blas=2.14=openblas
  - bleach=3.1.0=py_0
  - boost-cpp=1.70.0=h8e57a91_2
  - bzip2=1.0.8=h516909a_1
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h8022711_0
  - cfitsio=3.470=hb60a0a2_2
  - cftime=1.0.4.2=py37hc1659b7_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - colorama=0.4.1=py_0
  - cpuonly=1.0=0
  - cryptography=2.8=py37h72c5cf5_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.4=cuda10.0_0
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_4
  - dill=0.3.1.1=py37_0
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=he1b5a44_1004
  - fiona=1.8.9.post2=py37hdff7cfa_0
  - flake8=3.7.9=py37_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - freexl=1.0.5=h14c3975_1002
  - gdal=2.4.3=py37h5f563d9_9
  - geopandas=0.6.2=py_0
  - geos=3.7.2=he1b5a44_2
  - geotiff=1.5.1=hbd99317_7
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.7=h516909a_1
  - gitdb2=2.0.6=py_0
  - gitpython=3.0.5=py_0
  - glib=2.58.3=py37h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - h5py=2.10.0=nompi_py37h513d04c_100
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - idna=2.8=py37_1000
  - imagesize=1.1.0=py_0
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.3=py37h5ca1d4c_0
  - ipython=7.9.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.0=py_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - json5=0.8.5=py_0
  - jsonschema=3.1.1=py37_0
  - jupyter_client=5.3.3=py37_1
  - jupyter_core=4.5.0=py_0
  - jupyterlab=1.2.3=py_0
  - jupyterlab_server=1.0.6=py_0
  - kealib=1.4.10=h58c409b_1005
  - kiwisolver=1.1.0=py37hc9558a2_0
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.0=default_hde54327_4
  - libcurl=7.65.3=hda55be3_0
  - libdap4=3.20.4=hd3bb157_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=hdf63c60_0
  - libgdal=2.4.3=h2f07a13_9
  - libgfortran-ng=7.3.0=hdf63c60_2
  - libiconv=1.15=h516909a_1005
  - libkml=1.3.0=h4fcabce_1010
  - liblapack=3.8.0=14_openblas
  - liblapacke=3.8.0=14_openblas
  - libllvm8=8.0.1=hc9558a2_0
  - libllvm9=9.0.0=hc9558a2_3
  - libnetcdf=4.7.1=nompi_h94020b1_101
  - libopenblas=0.3.7=h6e990d7_3
  - libpng=1.6.37=hed695b0_0
  - libpq=11.5=hd9ab2ff_2
  - libsodium=1.0.17=h516909a_0
  - libspatialindex=1.9.3=he1b5a44_1
  - libspatialite=4.3.0a=h4f6d029_1032
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_0
  - libtiff=4.1.0=hc3755c2_1
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.9.1=hebb1f50_0
  - libxml2=2.9.10=hee79883_0
  - llvmlite=0.30.0=py37h8b12597_1
  - lz4-c=1.8.3=he1b5a44_1001
  - markupsafe=1.1.1=py37h516909a_0
  - matplotlib=3.1.2=py37_1
  - matplotlib-base=3.1.2=py37h250f245_1
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py37h516909a_1000
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37h516909a_0
  - more-itertools=7.2.0=py_0
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py37_0
  - nbdime=1.1.0=py37_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - netcdf4=1.5.3=py37hf3213d6_0
  - ninja=1.9.0=hc9558a2_1
  - notebook=6.0.1=py37_0
  - nspr=4.23=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numba=0.46.0=py37hb3f55d8_1
  - numpy=1.17.3=py37h95a1406_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h981e76c_2
  - openssl=1.1.1d=h516909a_0
  - packaging=19.2=py_0
  - pandas=0.25.3=py37hb3f55d8_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - pcre=8.43=he1b5a44_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pillow=6.2.1=py37h6b7be26_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - poppler=0.67.0=h14e79db_8
  - poppler-data=0.4.9=1
  - postgresql=11.5=hc63931a_2
  - proj=6.2.1=hc80f0dc_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycodestyle=2.5.0=py_0
  - pycparser=2.19=py37_1
  - pyflakes=2.1.1=py_0
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.5=py_0
  - pyproj=2.4.1=py37h12732c1_1
  - pyqt=5.12.3=py37hcca6a23_1
  - pyrsistent=0.15.5=py37h516909a_0
  - pysocks=1.7.1=py37_0
  - python=3.7.3=h33d41f4_1
  - python-dateutil=2.8.1=py_0
  - pytorch=1.3.1=py3.7_cpu_0
  - pytz=2019.3=py_0
  - pyzmq=18.1.1=py37h1768529_0
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py37_1
  - rtree=0.9.1=py37h7b0cdae_0
  - scikit-learn=0.21.3=py37hcdab131_0
  - scipy=1.3.2=py37h921218d_0
  - send2trash=1.5.0=py_0
  - setuptools=41.6.0=py37_1
  - shapely=1.6.4=py37hec07ddf_1006
  - six=1.13.0=py37_0
  - smmap2=2.0.5=py_0
  - snowballstemmer=2.0.0=py_0
  - sphinx=2.2.1=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sqlite=3.30.1=hcee41ef_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.9=hed695b0_1003
  - torchvision=0.4.2=py37_cpu
  - tornado=6.0.3=py37h516909a_0
  - tqdm=4.38.0=py_0
  - traitlets=4.3.3=py37_0
  - tzcode=2019a=h516909a_1002
  - urllib3=1.25.7=py37_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - xerces-c=3.2.2=h8412b87_1004
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zeromq=4.3.2=he1b5a44_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - sphinx-rtd-theme==0.4.3

